[build-system]
build-backend = "setuptools.build_meta"
requires = [
    "setuptools-scm>=9",
    "setuptools>=80",
]

[project]
authors = [
    { email = "michimussato@gmail.com", name = "Michael Mussato" },
]
classifiers = [
    "Development Status :: 4 - Beta",
    "Framework :: OpenStudioLandscapes",
    "Programming Language :: Python",
]
dependencies = [
    "dagster==1.9.11",
    "OpenImageIO",
#    "OpenEXR",
    "OpenStudioLandscapes-DagsterCodeLocation-JobProcessor @ git+https://github.com/michimussato/OpenStudioLandscapes-DagsterCodeLocation-JobProcessor.git@main",
    "OpenStudioLandscapes-DagsterCodeLocation-StreamingProcess @ git+https://github.com/michimussato/OpenStudioLandscapes-DagsterCodeLocation-StreamingProcess.git",
]
description = "Run post-render jobs in Dagster."
dynamic = [
    "version",
]
license-files = [
    "LICENSE.txt",
]
maintainers = [
    { email = "michimussato@gmail.com", name = "Michael Mussato" },
]
name = "OpenStudioLandscapes-DagsterCodeLocation-ShotProcessor"
requires-python = ">=3.11"

[project.optional-dependencies]
dev = [
    "dagster-webserver==1.9.11",
    "pytest",
    "OpenStudioLandscapes @ git+https://github.com/michimussato/OpenStudioLandscapes.git",
]

[project.readme]
content-type = "text/markdown; charset=UTF-8"
file = "README.md"

[project.scripts]
shot-processor = "OpenStudioLandscapes.DagsterCodeLocation.ShotProcessor.cli:run"
kitsu-submit = "OpenStudioLandscapes.DagsterCodeLocation.ShotProcessor.jobs.mov_to_kitsu.resources.kitsu_submission_cli:run"

[project.urls]
Homepage = "https://github.com/michimussato/OpenStudioLandscapes-DagsterCodeLocation-ShotProcessor"

[tool.setuptools]
include-package-data = true
#packages = [
#    "OpenStudioLandscapes.DagsterCodeLocation.ShotProcessor",
#]
platforms = [
    "Linux",
]

#[tool.setuptools.package-dir]
#"" = "src"

[tool.setuptools.packages.find]
exclude = [
    "tests",
]
namespaces = true
where = [
    "src",
]
#include = ["OpenStudioLandscapes.DagsterCodeLocation.ShotProcessor"]
include = ["OpenStudioLandscapes.DagsterCodeLocation.*"]
